version: '3.8'

services:
  # Веб-сервіс гри "Ловець"
  catcher-game:
    build: .
    container_name: catcher-game-container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - game-network

  # Redis сервіс для збереження результатів
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - game-network
    command: redis-server --appendonly yes

  # Додатковий сервіс - веб-інтерфейс для перегляду статистики
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - game-network

volumes:
  redis_data:

networks:
  game-network:
    driver: bridge
